num1=input("enter a number :")
num2=input("enter second number :")
print(type(num1))
print(type(num2))
# print(num1*10)
# print(num1+10)
# print(num1/10)
num3=int(input("enter a number :"))
num4=int(input("enter second number :"))
print(type(num3))
print(type(num4))
num5=float(input("enter fifith number :"))
num6=float(input("enter the sixth number :"))
print(type(num5))
print(type(num6))
print(num5*10)
print(num6+10)
print(num5/10)
